version: "3.8"
services:
  strapidb:
    image: sarenza/strapidb:1.0.0
    container_name: strapidb
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile.postgresql
      args:
        buildno: 1
    environment:
      - POSTGRES_PASSWORD=azertyuiop
    ports:
      - 5432:5432
    volumes:
        - strapidb:/var/lib/postgresql/data
    networks:
      - strapi
  # strapi:
  #   container_name: strapi
  #   image: srzlab.azurecr.io/strapi:1.0.0
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped
  #   depends_on: 
  #     - strapidb
  #   build:
  #     context: ./strapi
  #     dockerfile: Dockerfile.strapi
  #   environment:
  #     - DATABASE_HOST=strapidb
  #     - NODE_ENV=development
  #   ports:
  #     - 2337:9337
  #   networks:
  #     - strapi
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ylorho@sarenza.com
      - PGADMIN_DEFAULT_PASSWORD=azertyuiop
    ports:
      - 8081:57598
      - 70:80
      - 433:443
    networks:
      - strapi
networks:
  strapi:
volumes:
    # Must be created out of this docker-compose context 
    #   -> docker volume create --name strapidb -d local
    strapidb:
      external: true